import React from 'react';
import Link from 'next/link';
import { ArrowLeft, Scale } from 'lucide-react';

export const metadata = {
  title: 'Terms & Conditions | IPMASTER',
  description: 'Understand the legal terms of service, government registry fees policies, and attorney advisory boundaries of IPMASTER.'
};

export default function TermsAndConditions() {
  return (
    <div className="relative pb-24">
      {/* Decorative gradients */}
      <div className="absolute top-[-100px] left-[5%] w-[300px] h-[300px] bg-accent/5 blur-[100px] rounded-full pointer-events-none" />

      <section className="max-w-4xl mx-auto px-4 py-16 w-full flex flex-col gap-8">
        
        {/* Back Link */}
        <Link
          href="/"
          className="inline-flex items-center gap-1.5 text-xs font-semibold text-muted-foreground hover:text-accent self-start"
        >
          <ArrowLeft className="h-3.5 w-3.5" /> Back to Home
        </Link>

        {/* Header */}
        <div className="border-b border-gray-150 dark:border-border/60 pb-6 flex items-center gap-4">
          <div className="p-3 rounded-2xl bg-accent/10 text-accent shrink-0">
            <Scale className="h-6 w-6" />
          </div>
          <div>
            <h1 className="text-2xl md:text-3xl font-extrabold text-primary dark:text-white">Terms of Legal Service</h1>
            <p className="text-xs text-muted-foreground mt-1">Last Updated: May 2026 &bull; Advisory Service Bounds</p>
          </div>
        </div>

        {/* Body Content */}
        <div className="prose dark:prose-invert text-xs md:text-sm leading-relaxed text-slate-700 dark:text-slate-300 flex flex-col gap-6">
          <p>
            Welcome to <strong>IPMASTER</strong>. By accessing our website, analyzing names using our interactive search simulator, or booking strategic consultations, you agree to adhere to the following statutory terms of service.
          </p>

          <h2 className="text-sm font-bold text-primary dark:text-white uppercase tracking-wider border-b border-gray-100 dark:border-border/40 pb-2">
            1. Scope of AI Search Simulator
          </h2>
          <p>
            The trademark score indices, phonetic scans, and strength reports generated by our <strong>Trademark Availability Checker</strong> are simulated results designed for informational guidelines. They do not constitute formal, binding legal opinions. A final availability check is subject to statutory registry examiner reviews under the controller general.
          </p>

          <h2 className="text-sm font-bold text-primary dark:text-white uppercase tracking-wider border-b border-gray-100 dark:border-border/40 pb-2">
            2. Government Fees & Concessions
          </h2>
          <p>
            Official government registry fees (charged by the Trademark Registry, Patent Office, or tax departments) are paid directly to state portals. <strong>Government filing fees are strictly non-refundable</strong> once processed, regardless of whether your application faces subsequent examiner objections or oppositions.
          </p>

          <h2 className="text-sm font-bold text-primary dark:text-white uppercase tracking-wider border-b border-gray-100 dark:border-border/40 pb-2">
            3. Bar Council & Legal Privileges
          </h2>
          <p>
            While preliminary consults and document cataloging are supported by legal specialists, formal judicial representations before Courts of Law or Appellate Boards are directed through Bar-registered advocates under separate vakalatnama frameworks, strictly complying with the Bar Council of India codes of conduct.
          </p>
        </div>

      </section>
    </div>
  );
}
